import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Headers from "@/components/Header/Headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-wrap">
          <div className="w-[15%] h-screen ">
            <Sidebar />
          </div>
          <div className="grow h-screen flex flex-col">
            <Headers />
            <div className="overflow-x-scroll bg-sky-100 rounded-2xl scrollbar-hide">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
